services:
  nginx:
    image: nginx:mainline-alpine
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=nginx
    - NGINX_PORT=80
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0-amd64
    ports:
    - "4180:4180"
    env_file:
      - .env
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=http://0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8080/oauth2/callback
      - OAUTH2_PROXY_UPSTREAM=http://localhost:8080
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_COOKIE_SECRET=$OAUTH2_PROXY_COOKIE_SECRET
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_CLIENT_ID=$OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=$OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_AZURE_TENANT=$OAUTH2_PROXY_AZURE_TENANT
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/$OAUTH2_PROXY_AZURE_TENANT/v2.0

